python ../code/pafscaff.py dochtml newlog

python ../code/pafscaff.py --description | sed 's/^/# /' > ../PAFScaff.md
echo >> ../PAFScaff.md

echo '```' >> ../PAFScaff.md
python ../code/pafscaff.py --details >> ../PAFScaff.md
echo '```' >> ../PAFScaff.md
echo >> ../PAFScaff.md
echo 'For a better rendering and navigation of this document, please download and open [`./docs/pafscaff.docs.html`](./docs/pafscaff.docs.html), or visit <https://slimsuite.github.io/pafscaff/>.' >> ../PAFScaff.md
echo 'Documentation can also be generated by running PAFScaff with the `dochtml=T` option. (R and pandoc must be installed - see below.)' >> ../PAFScaff.md
echo >> ../PAFScaff.md
echo '## Introduction' >> ../PAFScaff.md
echo >> ../PAFScaff.md
grep -A 10000 assembly pafscaff.docs.Rmd >> ../PAFScaff.md

cp pafscaff.docs.html ../index.html
